base_model: models/mol-moe-base-6x1b
run_name: mol-moe-6x1b
output_model_name: mol-moe-6x1b
output_path: models/mol-moe-6x1b
wandb_project_name: biogen-mila-mol-moe
lr: 1e-3
batch_size: 64
max_gpu_batch_size: 4
seed: 42
lr_scheduler_type: linear
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-8
epochs: 1
enable_resume: True
eval_steps: 10
logging_steps: 10
save_steps: 10
patience: 50
min_delta: 0.025
num_samples: 100000
beta: 0.05
tasks: ['JNK3', 'DRD2', 'GSK3B', 'CYP2C19_Veith', 'CYP2D6_Veith']
max_output_len: 64
top_p: 0.9
temperature: 1.0
max_checkpoints: 4
is_moe: True