base_model: meta-llama/Llama-3.2-1B
run_name: ric-offline-mol-llama-1b
output_model_name: ric-offline-mol-llama-1b
output_path: models/ric-offline-mol-llama-1b
wandb_project_name: biogen-mila-mol-moe
hf_dataset: datasets/ric-offline-molecules-3.5M
hf_dataset_text_field: prompt
lr: 2e-5
batch_size: 256
max_gpu_batch_size: 4
seed: 42
lr_scheduler_type: linear
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-8
epochs: 1
enable_resume: True
max_seq_len: 256
warmup_steps: 10
packing: True
eval_steps: 10
logging_steps: 10
save_steps: 10