base_model: models/mol-llama-1b
run_name: mol-llama-1b-JNK3
output_model_name: mol-llama-1b-JNK3
output_path: models/mol-llama-1b-JNK3
wandb_project_name: biogen-mila-mol-moe
lr: 1e-6
batch_size: 128
max_gpu_batch_size: 4
seed: 42
lr_scheduler_type: linear
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-8
epochs: 1
enable_resume: True
eval_steps: 10
logging_steps: 10
save_steps: 10
patience: 50
min_delta: 0.025
num_samples: 100000
beta: 0.2
tasks: ['JNK3']
max_output_len: 64
top_p: 0.9
temperature: 1.0
max_checkpoints: 4